export enum Events {
  GAS = 'GAS',
  BRAKE = 'BRAKE',
  SET_CAMERA_FOLLOW = 'SET_CAMERA_FOLLOW',
  START_RACE = 'START_RACE',
  REMOVE_BODY = 'REMOVE_BODY',
  REMOVE_INSTANCE = 'REMOVE_INSTANCE',
  CHECKPOINT_PASSED = 'CHECKPOINT_PASSED',
  UPDATE_SPEED = 'UPDATE_SPEED',
}
